// This file is @generated by prost-build.
// Android 14 (AOSP) Update Engine protobuf definitions.
// Source: system/update_engine/update_metadata.proto
//
// IMPORTANT: Field numbers and types must match AOSP exactly!
// The wire format is: (field_number << 3) | wire_type

#![allow(clippy::all)]
#![allow(dead_code)]
#![allow(non_camel_case_types)]
#![allow(unused_variables)]

/// An Extent represents a range of blocks on disk.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Extent {
    /// Starting block number.
    #[prost(uint64, optional, tag = "1")]
    pub start_block: ::core::option::Option<u64>,
    /// Number of blocks in the extent.
    #[prost(uint64, optional, tag = "2")]
    pub num_blocks: ::core::option::Option<u64>,
}

/// Signatures for update verification.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Signatures {
    #[prost(message, repeated, tag = "1")]
    pub signatures: ::prost::alloc::vec::Vec<signatures::Signature>,
}

/// Nested types for Signatures.
pub mod signatures {
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct Signature {
        #[prost(uint32, optional, tag = "1")]
        pub version: ::core::option::Option<u32>,
        #[prost(bytes = "vec", optional, tag = "2")]
        pub data: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
        /// Unpadded size of the signature.
        #[prost(fixed32, optional, tag = "3")]
        pub unpadded_signature_size: ::core::option::Option<u32>,
    }
}

/// Information about a partition (size and hash).
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PartitionInfo {
    /// Size of the partition in bytes.
    #[prost(uint64, optional, tag = "1")]
    pub size: ::core::option::Option<u64>,
    /// Verity hash tree (SHA256).
    #[prost(bytes = "vec", optional, tag = "2")]
    pub hash: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
}

/// An installation operation to apply to a partition.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InstallOperation {
    /// Type of operation.
    #[prost(enumeration = "install_operation::Type", required, tag = "1")]
    pub r#type: i32,
    /// Data offset in the payload for this operation.
    #[prost(uint64, optional, tag = "2")]
    pub data_offset: ::core::option::Option<u64>,
    /// Length of the data in the payload.
    #[prost(uint64, optional, tag = "3")]
    pub data_length: ::core::option::Option<u64>,
    /// Source extents (for MOVE, BSDIFF, SOURCE_COPY, etc).
    #[prost(message, repeated, tag = "4")]
    pub src_extents: ::prost::alloc::vec::Vec<Extent>,
    /// Source length in bytes.
    #[prost(uint64, optional, tag = "5")]
    pub src_length: ::core::option::Option<u64>,
    /// Destination extents.
    #[prost(message, repeated, tag = "6")]
    pub dst_extents: ::prost::alloc::vec::Vec<Extent>,
    /// Destination length in bytes.
    #[prost(uint64, optional, tag = "7")]
    pub dst_length: ::core::option::Option<u64>,
    /// Hash of the data blob (SHA256).
    #[prost(bytes = "vec", optional, tag = "8")]
    pub data_sha256_hash: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    /// Hash of the source data (SHA256).
    #[prost(bytes = "vec", optional, tag = "9")]
    pub src_sha256_hash: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
}

/// Operation types - MUST match AOSP exactly.
pub mod install_operation {
    #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
    #[repr(i32)]
    pub enum Type {
        Replace = 0,
        ReplaceBz = 1,
        /// Deprecated
        Move = 2,
        /// Deprecated
        Bsdiff = 3,
        SourceCopy = 4,
        SourceBsdiff = 5,
        Zero = 6,
        Discard = 7,
        ReplaceXz = 8,
        Puffdiff = 9,
        BrotliBsdiff = 10,
        Zucchini = 11,
        Lz4diffBsdiff = 12,
        Lz4diffPuffdiff = 13,
    }

    impl Type {
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Type::Replace => "REPLACE",
                Type::ReplaceBz => "REPLACE_BZ",
                Type::Move => "MOVE",
                Type::Bsdiff => "BSDIFF",
                Type::SourceCopy => "SOURCE_COPY",
                Type::SourceBsdiff => "SOURCE_BSDIFF",
                Type::Zero => "ZERO",
                Type::Discard => "DISCARD",
                Type::ReplaceXz => "REPLACE_XZ",
                Type::Puffdiff => "PUFFDIFF",
                Type::BrotliBsdiff => "BROTLI_BSDIFF",
                Type::Zucchini => "ZUCCHINI",
                Type::Lz4diffBsdiff => "LZ4DIFF_BSDIFF",
                Type::Lz4diffPuffdiff => "LZ4DIFF_PUFFDIFF",
            }
        }
    }
}

/// Describes the update for a single partition.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PartitionUpdate {
    /// Partition name (e.g., "system", "vendor", "boot").
    #[prost(string, required, tag = "1")]
    pub partition_name: ::prost::alloc::string::String,
    /// Whether to run postinstall scripts.
    #[prost(bool, optional, tag = "2")]
    pub run_postinstall: ::core::option::Option<bool>,
    /// Postinstall path.
    #[prost(string, optional, tag = "3")]
    pub postinstall_path: ::core::option::Option<::prost::alloc::string::String>,
    /// Filesystem type for postinstall mount.
    #[prost(string, optional, tag = "4")]
    pub filesystem_type: ::core::option::Option<::prost::alloc::string::String>,
    /// Postinstall arguments.
    #[prost(message, repeated, tag = "5")]
    pub new_partition_signature: ::prost::alloc::vec::Vec<signatures::Signature>,
    /// Old partition info (for delta updates).
    #[prost(message, optional, tag = "6")]
    pub old_partition_info: ::core::option::Option<PartitionInfo>,
    /// New partition info (target state).
    #[prost(message, optional, tag = "7")]
    pub new_partition_info: ::core::option::Option<PartitionInfo>,
    /// List of install operations.
    #[prost(message, repeated, tag = "8")]
    pub operations: ::prost::alloc::vec::Vec<InstallOperation>,
    /// Whether postinstall is optional.
    #[prost(bool, optional, tag = "9")]
    pub postinstall_optional: ::core::option::Option<bool>,
    /// Hash tree parameters for dm-verity.
    #[prost(message, optional, tag = "10")]
    pub hash_tree_data_extent: ::core::option::Option<Extent>,
    #[prost(message, optional, tag = "11")]
    pub hash_tree_extent: ::core::option::Option<Extent>,
    #[prost(string, optional, tag = "12")]
    pub hash_tree_algorithm: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(bytes = "vec", optional, tag = "13")]
    pub hash_tree_salt: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    /// FEC (Forward Error Correction) parameters.
    #[prost(message, optional, tag = "14")]
    pub fec_data_extent: ::core::option::Option<Extent>,
    #[prost(message, optional, tag = "15")]
    pub fec_extent: ::core::option::Option<Extent>,
    #[prost(uint32, optional, tag = "16")]
    pub fec_roots: ::core::option::Option<u32>,
    /// Version string for this partition.
    #[prost(string, optional, tag = "17")]
    pub version: ::core::option::Option<::prost::alloc::string::String>,
    /// Merge operations for VAB.
    #[prost(message, repeated, tag = "18")]
    pub merge_operations: ::prost::alloc::vec::Vec<CowMergeOperation>,
    /// Estimated COW size.
    #[prost(uint64, optional, tag = "19")]
    pub estimate_cow_size: ::core::option::Option<u64>,
}

/// COW merge operation for Virtual A/B.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CowMergeOperation {
    #[prost(enumeration = "cow_merge_operation::Type", optional, tag = "1")]
    pub r#type: ::core::option::Option<i32>,
    #[prost(message, optional, tag = "2")]
    pub src_extent: ::core::option::Option<Extent>,
    #[prost(message, optional, tag = "3")]
    pub dst_extent: ::core::option::Option<Extent>,
    #[prost(uint32, optional, tag = "4")]
    pub src_offset: ::core::option::Option<u32>,
}

pub mod cow_merge_operation {
    #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
    #[repr(i32)]
    pub enum Type {
        CowCopy = 0,
        CowXor = 1,
        CowReplace = 2,
    }
}

/// Dynamic partition group.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DynamicPartitionGroup {
    /// Group name.
    #[prost(string, required, tag = "1")]
    pub name: ::prost::alloc::string::String,
    /// Maximum size of the group.
    #[prost(uint64, optional, tag = "2")]
    pub size: ::core::option::Option<u64>,
    /// List of partition names in this group.
    #[prost(string, repeated, tag = "3")]
    pub partition_names: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}

/// Dynamic partition metadata.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DynamicPartitionMetadata {
    /// List of partition groups.
    #[prost(message, repeated, tag = "1")]
    pub groups: ::prost::alloc::vec::Vec<DynamicPartitionGroup>,
    /// Whether snapshot (VAB) is enabled.
    #[prost(bool, optional, tag = "2")]
    pub snapshot_enabled: ::core::option::Option<bool>,
    /// Whether VABC (Virtual A/B Compression) is enabled.
    #[prost(bool, optional, tag = "3")]
    pub vabc_enabled: ::core::option::Option<bool>,
    /// VABC compression algorithm.
    #[prost(string, optional, tag = "4")]
    pub vabc_compression_param: ::core::option::Option<::prost::alloc::string::String>,
    /// COW format version.
    #[prost(uint32, optional, tag = "5")]
    pub cow_version: ::core::option::Option<u32>,
    /// Feature set.
    #[prost(message, optional, tag = "6")]
    pub vabc_feature_set: ::core::option::Option<VabcFeatureSet>,
    /// Compression factor.
    #[prost(uint64, optional, tag = "7")]
    pub compression_factor: ::core::option::Option<u64>,
}

/// Virtual A/B compression feature set.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct VabcFeatureSet {
    #[prost(bool, optional, tag = "1")]
    pub threaded: ::core::option::Option<bool>,
    #[prost(bool, optional, tag = "2")]
    pub batch_writes: ::core::option::Option<bool>,
}

/// APEX package info.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ApexInfo {
    #[prost(string, optional, tag = "1")]
    pub package_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int64, optional, tag = "2")]
    pub version: ::core::option::Option<i64>,
    #[prost(bool, optional, tag = "3")]
    pub is_compressed: ::core::option::Option<bool>,
    #[prost(int64, optional, tag = "4")]
    pub decompressed_size: ::core::option::Option<i64>,
}

/// APEX metadata container.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ApexMetadata {
    #[prost(message, repeated, tag = "1")]
    pub apex_info: ::prost::alloc::vec::Vec<ApexInfo>,
}

/// The main manifest message describing the entire OTA update.
///
/// CRITICAL: Field numbers MUST match AOSP update_metadata.proto exactly!
/// Field numbers are part of the wire format.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeltaArchiveManifest {
    // =========================================================================
    // DEPRECATED FIELDS (kept for backwards compatibility)
    // These were used in older Chrome OS updates, not Android ROMs.
    // =========================================================================
    
    /// Deprecated: rootfs install operations.
    #[prost(message, repeated, tag = "1")]
    pub install_operations: ::prost::alloc::vec::Vec<InstallOperation>,
    
    /// Deprecated: kernel install operations.
    #[prost(message, repeated, tag = "2")]
    pub kernel_install_operations: ::prost::alloc::vec::Vec<InstallOperation>,
    
    /// Block size (usually 4096).
    #[prost(uint32, optional, tag = "3", default = "4096")]
    pub block_size: ::core::option::Option<u32>,
    
    /// Deprecated: total blocks to update (rootfs).
    #[prost(uint64, optional, tag = "4")]
    pub signatures_offset: ::core::option::Option<u64>,
    
    /// Deprecated: signatures size.
    #[prost(uint64, optional, tag = "5")]
    pub signatures_size: ::core::option::Option<u64>,
    
    // NOTE: Fields 6-11 are deprecated Chrome OS fields.
    // Android ROMs don't use them, but we need placeholders for wire format.
    
    /// Deprecated: old kernel info.
    #[prost(message, optional, tag = "6")]
    pub old_kernel_info: ::core::option::Option<PartitionInfo>,
    
    /// Deprecated: new kernel info.
    #[prost(message, optional, tag = "7")]
    pub new_kernel_info: ::core::option::Option<PartitionInfo>,
    
    /// Deprecated: old rootfs info.
    #[prost(message, optional, tag = "8")]
    pub old_rootfs_info: ::core::option::Option<PartitionInfo>,
    
    /// Deprecated: new rootfs info.
    #[prost(message, optional, tag = "9")]
    pub new_rootfs_info: ::core::option::Option<PartitionInfo>,
    
    // =========================================================================
    // VERSION 2+ FIELDS (Android 5.0+)
    // =========================================================================
    
    /// Minor version of the manifest format.
    #[prost(uint32, optional, tag = "12", default = "0")]
    pub minor_version: ::core::option::Option<u32>,
    
    /// List of partition updates (Android 5.0+).
    /// This is the main field for modern Android updates!
    #[prost(message, repeated, tag = "13")]
    pub partitions: ::prost::alloc::vec::Vec<PartitionUpdate>,
    
    /// Maximum allowed timestamp for the update (anti-rollback).
    #[prost(int64, optional, tag = "14")]
    pub max_timestamp: ::core::option::Option<i64>,
    
    /// Dynamic partition metadata (Android 10+).
    #[prost(message, optional, tag = "15")]
    pub dynamic_partition_metadata: ::core::option::Option<DynamicPartitionMetadata>,
    
    /// Whether this is a partial update.
    #[prost(bool, optional, tag = "16")]
    pub partial_update: ::core::option::Option<bool>,
    
    /// APEX info for module updates.
    #[prost(message, repeated, tag = "17")]
    pub apex_info: ::prost::alloc::vec::Vec<ApexInfo>,
    
    /// Security patch level string (e.g., "2024-01-05").
    #[prost(string, optional, tag = "18")]
    pub security_patch_level: ::core::option::Option<::prost::alloc::string::String>,
}
