// This file is @generated by prost-build.
// It contains the Rust structs for Android OTA payload.bin parsing.
// Based on: update_metadata.proto from AOSP

#![allow(clippy::all)]
#![allow(dead_code)]
#![allow(non_camel_case_types)]

/// An Extent represents a range of blocks on disk.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Extent {
    #[prost(uint64, optional, tag = "1")]
    pub start_block: ::core::option::Option<u64>,
    #[prost(uint64, optional, tag = "2")]
    pub num_blocks: ::core::option::Option<u64>,
}

/// Signatures for update verification.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Signatures {
    #[prost(message, repeated, tag = "1")]
    pub signatures: ::prost::alloc::vec::Vec<signatures::Signature>,
}

/// Nested message and enum types in `Signatures`.
pub mod signatures {
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct Signature {
        #[prost(uint32, optional, tag = "1")]
        pub version: ::core::option::Option<u32>,
        #[prost(bytes = "vec", optional, tag = "2")]
        pub data: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
        #[prost(uint32, optional, tag = "3")]
        pub unpadded_signature_size: ::core::option::Option<u32>,
    }
}

/// Information about a partition.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PartitionInfo {
    #[prost(uint64, optional, tag = "1")]
    pub size: ::core::option::Option<u64>,
    #[prost(bytes = "vec", optional, tag = "2")]
    pub hash: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
}

/// An installation operation.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InstallOperation {
    #[prost(enumeration = "install_operation::Type", required, tag = "1")]
    pub r#type: i32,
    #[prost(uint64, optional, tag = "2")]
    pub data_offset: ::core::option::Option<u64>,
    #[prost(uint64, optional, tag = "3")]
    pub data_length: ::core::option::Option<u64>,
    #[prost(message, repeated, tag = "4")]
    pub src_extents: ::prost::alloc::vec::Vec<Extent>,
    #[prost(uint64, optional, tag = "5")]
    pub src_length: ::core::option::Option<u64>,
    #[prost(message, repeated, tag = "6")]
    pub dst_extents: ::prost::alloc::vec::Vec<Extent>,
    #[prost(uint64, optional, tag = "7")]
    pub dst_length: ::core::option::Option<u64>,
    #[prost(bytes = "vec", optional, tag = "8")]
    pub data_sha256_hash: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes = "vec", optional, tag = "9")]
    pub src_sha256_hash: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
}

/// Nested message and enum types in `InstallOperation`.
pub mod install_operation {
    #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
    #[repr(i32)]
    pub enum Type {
        Replace = 0,
        ReplaceBz = 1,
        Move = 2,
        Bsdiff = 3,
        SourceCopy = 4,
        SourceBsdiff = 5,
        Zero = 6,
        Discard = 7,
        ReplaceXz = 8,
        Puffdiff = 9,
        BrotliBsdiff = 10,
        Zucchini = 11,
        Lz4diffBsdiff = 12,
        Lz4diffPuffdiff = 13,
    }
    
    impl Type {
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Type::Replace => "REPLACE",
                Type::ReplaceBz => "REPLACE_BZ",
                Type::Move => "MOVE",
                Type::Bsdiff => "BSDIFF",
                Type::SourceCopy => "SOURCE_COPY",
                Type::SourceBsdiff => "SOURCE_BSDIFF",
                Type::Zero => "ZERO",
                Type::Discard => "DISCARD",
                Type::ReplaceXz => "REPLACE_XZ",
                Type::Puffdiff => "PUFFDIFF",
                Type::BrotliBsdiff => "BROTLI_BSDIFF",
                Type::Zucchini => "ZUCCHINI",
                Type::Lz4diffBsdiff => "LZ4DIFF_BSDIFF",
                Type::Lz4diffPuffdiff => "LZ4DIFF_PUFFDIFF",
            }
        }
    }
}

/// Describes the update to apply to a single partition.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PartitionUpdate {
    #[prost(string, required, tag = "1")]
    pub partition_name: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "7")]
    pub new_partition_info: ::core::option::Option<PartitionInfo>,
    #[prost(message, repeated, tag = "8")]
    pub operations: ::prost::alloc::vec::Vec<InstallOperation>,
    #[prost(message, optional, tag = "6")]
    pub old_partition_info: ::core::option::Option<PartitionInfo>,
    #[prost(bool, optional, tag = "14")]
    pub estimate_cow_size: ::core::option::Option<bool>,
    #[prost(uint64, optional, tag = "15")]
    pub estimate_op_count_max: ::core::option::Option<u64>,
    #[prost(uint64, optional, tag = "20")]
    pub hash_tree_data_extent_start_block: ::core::option::Option<u64>,
    #[prost(uint64, optional, tag = "21")]
    pub hash_tree_data_extent_num_blocks: ::core::option::Option<u64>,
    #[prost(uint64, optional, tag = "22")]
    pub hash_tree_extent_start_block: ::core::option::Option<u64>,
    #[prost(uint64, optional, tag = "23")]
    pub hash_tree_extent_num_blocks: ::core::option::Option<u64>,
    #[prost(bytes = "vec", optional, tag = "24")]
    pub hash_tree_algorithm: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes = "vec", optional, tag = "25")]
    pub hash_tree_salt: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(uint64, optional, tag = "26")]
    pub fec_data_extent_start_block: ::core::option::Option<u64>,
    #[prost(uint64, optional, tag = "27")]
    pub fec_data_extent_num_blocks: ::core::option::Option<u64>,
    #[prost(uint64, optional, tag = "28")]
    pub fec_extent_start_block: ::core::option::Option<u64>,
    #[prost(uint64, optional, tag = "29")]
    pub fec_extent_num_blocks: ::core::option::Option<u64>,
    #[prost(uint32, optional, tag = "30")]
    pub fec_roots: ::core::option::Option<u32>,
    #[prost(string, optional, tag = "31")]
    pub version: ::core::option::Option<::prost::alloc::string::String>,
}

/// A group of dynamic partitions.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DynamicPartitionGroup {
    #[prost(string, required, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(uint64, optional, tag = "2")]
    pub size: ::core::option::Option<u64>,
    #[prost(string, repeated, tag = "3")]
    pub partition_names: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}

/// Metadata for dynamic partitioning.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DynamicPartitionMetadata {
    #[prost(message, repeated, tag = "1")]
    pub groups: ::prost::alloc::vec::Vec<DynamicPartitionGroup>,
    #[prost(bool, optional, tag = "2")]
    pub snapshot_enabled: ::core::option::Option<bool>,
    #[prost(bool, optional, tag = "3")]
    pub vabc_enabled: ::core::option::Option<bool>,
    #[prost(string, optional, tag = "4")]
    pub vabc_compression_param: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(uint32, optional, tag = "5")]
    pub cow_version: ::core::option::Option<u32>,
}

/// APEX package information.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ApexInfo {
    #[prost(string, optional, tag = "1")]
    pub package_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int64, optional, tag = "2")]
    pub version: ::core::option::Option<i64>,
    #[prost(bool, optional, tag = "3")]
    pub is_compressed: ::core::option::Option<bool>,
    #[prost(int64, optional, tag = "4")]
    pub decompressed_size: ::core::option::Option<i64>,
}

/// APEX metadata.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ApexMetadata {
    #[prost(message, repeated, tag = "1")]
    pub apex_info: ::prost::alloc::vec::Vec<ApexInfo>,
}

/// Image information (deprecated but included for compatibility).
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ImageInfo {
    #[prost(string, optional, tag = "1")]
    pub board: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "2")]
    pub key: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "3")]
    pub channel: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "4")]
    pub version: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "5")]
    pub build_channel: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "6")]
    pub build_version: ::core::option::Option<::prost::alloc::string::String>,
}

/// The main message, describing the entire update manifest.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeltaArchiveManifest {
    /// Deprecated: install_operations for the kernel and rootfs partitions.
    #[prost(message, repeated, tag = "1")]
    pub install_operations: ::prost::alloc::vec::Vec<InstallOperation>,
    #[prost(message, repeated, tag = "2")]
    pub kernel_install_operations: ::prost::alloc::vec::Vec<InstallOperation>,
    /// Block size used (default 4096).
    #[prost(uint32, optional, tag = "3", default = "4096")]
    pub block_size: ::core::option::Option<u32>,
    /// Deprecated partition info fields.
    #[prost(message, optional, tag = "5")]
    pub old_kernel_info: ::core::option::Option<PartitionInfo>,
    #[prost(message, optional, tag = "6")]
    pub new_kernel_info: ::core::option::Option<PartitionInfo>,
    #[prost(message, optional, tag = "7")]
    pub old_rootfs_info: ::core::option::Option<PartitionInfo>,
    #[prost(message, optional, tag = "8")]
    pub new_rootfs_info: ::core::option::Option<PartitionInfo>,
    /// Deprecated image info fields.
    #[prost(message, optional, tag = "9")]
    pub old_image_info: ::core::option::Option<ImageInfo>,
    #[prost(message, optional, tag = "10")]
    pub new_image_info: ::core::option::Option<ImageInfo>,
    /// Minor version.
    #[prost(uint32, optional, tag = "12", default = "0")]
    pub minor_version: ::core::option::Option<u32>,
    /// List of partition updates.
    #[prost(message, repeated, tag = "13")]
    pub partitions: ::prost::alloc::vec::Vec<PartitionUpdate>,
    /// Maximum timestamp allowed for the update.
    #[prost(int64, optional, tag = "14")]
    pub max_timestamp: ::core::option::Option<i64>,
    /// Metadata for dynamic partitioning.
    #[prost(message, optional, tag = "15")]
    pub dynamic_partition_metadata: ::core::option::Option<DynamicPartitionMetadata>,
    /// If the payload is partial.
    #[prost(bool, optional, tag = "16")]
    pub partial_update: ::core::option::Option<bool>,
    /// APEX metadata.
    #[prost(message, repeated, tag = "17")]
    pub apex_info: ::prost::alloc::vec::Vec<ApexInfo>,
    /// Security patch level of the update.
    #[prost(string, optional, tag = "18")]
    pub security_patch_level: ::core::option::Option<::prost::alloc::string::String>,
}
